name: familiada
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Core audio player API
  just_audio: ^0.10.0

  # Linux implementation for just_audio v0.10+
  just_audio_mpv: ^0.1.0

  #just_audio: ^0.9.46
  flame_audio: 2.1.7
  provider: ^6.0.1
  window_manager: ^0.3.8  # Dodaj pakiet do zarządzania oknami

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/questions.json
    - assets/questions_andrzejki.json
    - assets/final_questions.json
    - assets/audio/
